# Generated by Django 5.2 on 2025-04-28 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblAreaOperacionSensores',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(default='N/A', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblEstatusSensores',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(default='N/A', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblModeloSensores',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(default='N/A', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblUnidadSensores',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(default='N/A', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblAltaSensores',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Tag', models.CharField(default='N/A', max_length=100, null=True)),
                ('Descripcion', models.CharField(default='N/A', max_length=100, null=True)),
                ('Comentario', models.CharField(default='N/A', max_length=100, null=True)),
                ('IDArea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblareaoperacionsensores')),
                ('IDEstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatussensores')),
                ('IDModelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblmodelosensores')),
                ('IDUnidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblunidadsensores')),
            ],
        ),
        migrations.CreateModel(
            name='tblDatoSensores',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Datos', models.CharField(default='N/A', max_length=100, null=True)),
                ('Fecha', models.DateField(null=True)),
                ('Hora', models.TimeField(default='00:00:00', null=True)),
                ('IDSensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblaltasensores')),
            ],
        ),
    ]
