# Generated by Django 5.2 on 2025-04-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblaltasensores',
            name='FechaInstalado',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tblaltasensores',
            name='FechaMantenimiento',
            field=models.DateField(null=True),
        ),
    ]
