# Generated by Django 5.2 on 2025-05-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_tblaltasensores_fechainstalado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblDatoLineaTostador',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NoLinea', models.CharField(default='N/A', max_length=100, null=True)),
                ('Folio', models.CharField(default='N/A', max_length=100, null=True)),
                ('TmpInicial', models.CharField(default='N/A', max_length=100, null=True)),
                ('TmpTostado', models.CharField(default='N/A', max_length=100, null=True)),
                ('TmpEnfriado', models.CharField(default='N/A', max_length=100, null=True)),
                ('TmpoElevado', models.CharField(default='N/A', max_length=100, null=True)),
                ('Operador', models.CharField(default='N/A', max_length=100, null=True)),
                ('BatchVerde', models.CharField(default='N/A', max_length=100, null=True)),
                ('CantAgua', models.CharField(default='N/A', max_length=100, null=True)),
                ('TempCorte', models.CharField(default='N/A', max_length=100, null=True)),
                ('PesoTostado', models.CharField(default='N/A', max_length=100, null=True)),
                ('Destino', models.CharField(default='N/A', max_length=100, null=True)),
                ('FechaYHora', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tblaltasensores',
            name='IDArea',
        ),
    ]
