# Generated by Django 5.1.3 on 2025-05-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_tbldatolineatostador_remove_tblaltasensores_idarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblFiltroTostador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filtro', models.IntegerField(default='N/A', null=True)),
            ],
        ),
    ]
